defaults:
  - defaults
  - optional local@_global_: local
  - _self_

hf_training:
  num_train_epochs: 1
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 32
  learning_rate: 1e-4
  warmup_steps: 0.05
  weight_decay: 0.1
  save_strategy: steps
  save_steps: 2400
  save_total_limit: 5
  logging_strategy: steps
  logging_steps: 50
  eval_strategy: steps
  eval_steps: 400
  report_to: tensorboard
  bf16: True
  max_grad_norm: 1.
  dataloader_num_workers: 1
  remove_unused_columns: False
  gradient_checkpointing: True


data:
  training_dataset: /beegfs/scratch/project/calmar/rpisco/datasets/agent_trajs_filtered.hf
  samples: 500000

collator_class: pisco.collator.AgentTrajCollator

collator_kwargs:
  compressor_max_length: 128  
  decoder_max_length: 512
  p_compress: 0.5

model:
  init_args:
    _target_: pisco.model.PISCO
    config:
      _target_: pisco.model.PISCOConfig
      decoder_model_name: ${decoder}
      compressor_model_name: ${compressor}
      compr_rate: 16
      compressor_mlp_hidden_dim: 4096
      lora_decoder: True
      lora_r_decoder: 64
      attn_implementation: "flash_attention_2"

compressor: Qwen/Qwen3-0.6B
decoder: Qwen/Qwen3-0.6B
exp_name: agentic_${decoder}_${compressor}_compress${collator_kwargs.p_compress}_${collator_kwargs.decoder_max_length}
out_dir: .